name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies (Playwright)
        run: |
          npm install
          npx playwright install --with-deps

      - name: Start Backend
        run: |
          cd server
          npm install
          nohup node index.js > backend.log 2>&1 &
        working-directory: ${{ github.workspace }}

      - name: Start Frontend
        run: |
          cd client
          npm install
          nohup npm start -- --port=3000 > frontend.log 2>&1 &
        working-directory: ${{ github.workspace }}

      - name: Wait for Backend
        run: |
          echo "Waiting for backend..."
          for i in {1..60}; do
            if curl -s http://localhost:5000/items; then
              echo "Backend is ready"
              break
            fi
            echo "Retrying backend... ($i)"
            sleep 3
          done

      - name: Wait for Frontend
        run: |
          echo "Waiting for frontend..."
          for i in {1..60}; do
            if curl -s http://localhost:3000 | grep -q '<!DOCTYPE html>'; then
              echo "Frontend is ready"
              break
            fi
            echo "Retrying frontend... ($i)"
            sleep 3
          done

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Print frontend log on failure
        if: failure()
        run: cat client/frontend.log || true

      - name: Print backend log on failure
        if: failure()
        run: cat server/backend.log || true

